default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mapfre
  username: postgres
  #username: postgres
  password: root
  host: localhost
  port: 5432



production:
  adapter: postgresql
  database: mapfre
  pool: 5
  timeout: 5000
  username: postgres


