default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mapfre



production:
  adapter: postgresql
  database: mapfre
  pool: 5
  timeout: 5000
  username: postgres
password: sivic
